name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["{{cookiecutter.python_version}}"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install
    - name: Run linting
      run: |
        poetry run ruff check .
        poetry run pyright
    - name: Run tests
      run: poetry run pytest tests/ --cov={{cookiecutter.project_slug}} --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v3
